# Use postgres/example user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: app
      MYSQL_DATABASE: app
